version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - ..:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=menu_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=menu_management.settings
      - DJANGO_ENV=production
      - STAFF_PASSWORD=test_staff_password
    command: gunicorn menu_management.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ../data:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=menu_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume: 