version: '3'
services:
  db:
    image: postgres:latest
    container_name: menu-management-test-db
    env_file:
      - ../menu_management/settings/env/.env.test
    environment:
      POSTGRES_DB: menu_management_test
    ports:
      - "5433:5432"  # Different port to avoid conflict with dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 